# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bfa70fe0-fb17-45f4-b2cf-b17de939d736";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bfa70fe0-fb17-45f4-b2cf-b17de939d736".device = "/dev/disk/by-uuid/bfa70fe0-fb17-45f4-b2cf-b17de939d736";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3690-A136";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a86e090b-8f6a-43ee-a9df-262ffa193a88"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
